import {
  type Game,
  type GameAnswer,
  getCurrentGameAnswer,
  getGame,
  isWordExists
} from '~/api/service';
import { identifyLastSyllable } from '~/api/service/word/syllabify.api';

export const postAnswer = (gameId: string, word: string): GameAnswer => {
  const game = getGame(gameId);
  const answer = {
    word,
    syllables: identifyLastSyllable(word),
    isCorrect: isCorrectAnswer(game!, word),
    isAutoGenerated: false
  };
  game!.answers.push(answer);
  return answer;
};

const isCorrectAnswer = (game: Game, word: string) => {
  const lastAnswer = getCurrentGameAnswer(game.answers);
  const lastSyllable = lastAnswer.syllables[lastAnswer.syllables.length - 1];
  if (!word.startsWith(lastSyllable)) {
    return false;
  }
  return isWordExists(word);
};
