import {
  type Game,
  type GameAnswer,
  getCurrentGameAnswer,
  getGame,
  isWordExists
} from '~/api/service';
import { identifyLastSyllable } from '~/api/service/word/syllabify.api';

export const postAnswer = (gameId: string, word: string): GameAnswer => {
  const game = getGame(gameId);
  const isCorrect = isCorrectAnswer(game!, word);
  const answer = {
    word,
    syllables: identifyLastSyllable(word),
    isAutoGenerated: false,
    isCorrect: isCorrect[0],
    note: isCorrect[1]
  };
  game!.answers.push(answer);
  return answer;
};

const isCorrectAnswer = (game: Game, word: string): [boolean, string?] => {
  const lastAnswer = getCurrentGameAnswer(game.answers);
  const lastSyllable = lastAnswer.syllables[lastAnswer.syllables.length - 1];
  if (!word.startsWith(lastSyllable)) {
    return [false, 'kata tidak valid.'];
  }

  const isWordPresent = isWordExists(word);
  if (!isWordPresent) {
    return [false, 'kata tidak ditemukan.'];
  }

  if (game.answers.find((answer) => answer.word === word)) {
    return [false, 'kata sudah pernah dijawab.'];
  }

  return [true];
};
