import type { Game, GameAnswer } from '~/api/service';

export const countCorrectAnswers = (answers: GameAnswer[]): number => {
  return answers.filter((ans) => ans.isCorrect && !ans.isAutoGenerated).length;
};

export const countAnswersAccuracy = (answers: GameAnswer[]): number => {
  const correctAnswers = countCorrectAnswers(answers);
  // -1 for the first answer (auto generated word)
  return Math.round((correctAnswers / (answers.length - 1)) * 100) || 0;
};

export const countAnswersSpeed = (game: Game): number => {
  const correctAnswers = countCorrectAnswers(game.answers);
  const duration = parseInt(game.option.duration);
  return correctAnswers / duration || 0;
};

export const getPerformance = (game: Game): string => {
  const speed = countAnswersSpeed(game);
  const accuracy = countAnswersAccuracy(game.answers);
  const performance = speed * accuracy;
  if (performance <= 20) return 'kurang';
  if (performance <= 50) return 'cukup';
  if (performance <= 70) return 'baik';
  if (performance <= 85) return 'hebat';
  return 'luar biasa';
};
