import {
  type Game,
  type GameAnswer,
  type GameOption,
  games,
  getRandomWord
} from '..';
import { identifyLastSyllable } from '../word/syllabify.api';

export const createGame = (option: GameOption): Game => {
  const id = generateId();
  const game: Game = {
    id,
    option,
    startAt: Date.now(),
    answers: [generateFirstWord()]
  };
  games.push(game);
  return game;
};

const generateId = (length = 8) => {
  const characters =
    'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789';
  let result = '';

  for (let i = 0; i < length; i++) {
    const randomIndex = Math.floor(Math.random() * characters.length);
    result += characters.charAt(randomIndex);
  }

  return result;
};

const generateFirstWord = (): GameAnswer => {
  const word = getRandomWord();
  const syllables = identifyLastSyllable(word);

  return {
    word,
    syllables,
    isAutoGenerated: true,
    isCorrect: true
  };
};
