export interface GameOption {
  duration: '30' | '60' | '90';
  allowSkip: 'yes' | 'no';
}

export interface Game {
  id: string;
  option: GameOption;
  startAt: number;
  answers: GameAnswer[];
  firstWord: GameAnswer;
}

export interface GameAnswer {
  word: string;
  syllables: string[];
  isCorrect: boolean;
  isAutoGenerated: boolean;
}

export const games: Game[] = [];

export * from './new-game.api';
export * from './get-game.api';
