import { type Game, type GameAnswer, type GameOption, games } from '.';

export const createGame = (option: GameOption): Game => {
  const id = generateId();
  const game: Game = {
    id,
    option,
    startAt: Date.now(),
    answers: [],
    firstWord: generateFirstWord()
  };
  games.push(game);
  return game;
};

const generateId = (length = 8) => {
  const characters =
    'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789';
  let result = '';

  for (let i = 0; i < length; i++) {
    const randomIndex = Math.floor(Math.random() * characters.length);
    result += characters.charAt(randomIndex);
  }

  return result;
};

const generateFirstWord = (): GameAnswer => {
  return {
    isAutoGenerated: true,
    isCorrect: true,
    syllables: ['ma.sya.ra.kat'],
    word: 'masyarakat'
  };
};
